### ISSUE TITLE
sanitize.conf seems to be truncated

### ISSUE THREAD

**Issue by vincentbernat** [jtkristoff/junos#1]
Hey!

sanitize.conf seems to be truncated. At least the export policy seems to be missing.

**Comment by jtkristoff** [comment]
I didn't think they were important, but for completeness I put the finishing touches on that section.  Thanks.

fixed in:  https://github.com/jtkristoff/junos/commit/c31b867cf1c0a4a8fed329866190a2ee8cd0a398
